apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: default
resources:
  - ../base
  - ./encrypted-github-docker.yaml
  - ./encrypted-docker-secret.yaml
patches:
  - path: ./patch-api-gateway-service.yaml
  - path: ./patch-customer-service.yaml
  - path: ./patch-order-service.yaml


