apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway-service
spec:
  template:
    spec:
      imagePullSecrets:
        - name: ghcr.io
      containers:
        - name: api-gateway-service
          image: "ghcr.io/skyglass/cloud-native-template-steps/api-gateway-service:0.1.0-SNAPSHOT"
